title: My Awesome Docs
description: A knowledge base for my project
theme: jekyll-rtd-theme
markdown: kramdown
url: "https://github.com/Cyber2499/JekyllResponse"
exclude:
  - Gemfile
  - Gemfile.lock

# Custom navigation order or sidebar tweaks can be added too
